[package]
name = "bitews"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["full"] }
tokio-tungstenite = "0.16.1"
# tokio-util = "0.6.9"
futures-util = "0.3.19"
futures-channel = "0.3.19"
url = "2.2.2"

[[example]]
name = "client"
