version: '3.3'
services:

  # bite:
  #   container_name: bite
  #   build: ../bite/
  #   ports:
  #       - '1984:1984'
  #   volumes:
  #       - ./chat-data:/data
  #   restart: on-failure

  bitews:
    container_name: bitews
    build: ./
    ports:
      - '1983:1983'
    volumes:
      - ./data:/data
    environment:
      - SERVER=0.0.0.0:1983
      - PROXY=bite:1984
    restart: on-failure
