version: '3.8'
services:
    bitews:
        container_name: bitews
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '1983:1983'
        volumes:
            - type: bind
              source: ./data
              target: /data
        environment:
            - SERVER=0.0.0.0:1983
            - PROXY=bite:1984 # You need a BITE server somewhere to proxy.
            - RUST_LOG=info
        restart: unless-stopped

    # bite:
    # [...]
